### ISSUE TITLE
reading Calls and SMS on Samsung GT-C3510 (Player Light)

### ISSUE THREAD

**Issue by nazmifr** [gammu/gammu#221] opened 2016-07-07 06:28 UTC
Hi,
I'm using/testing Wammu, it looks awesome compared to the unusable garbage that the samsung PC studio thing was under windows...

I tried reading the Contacts on that phone, it worked nicely, then I tried reading the Calls and after about a minute it failed. When I try for the Messages or the Calendar the loading windows comes up but nothing happen, then I have "Wammu is not responding".

Is this issue something that can be fixed ? (if it's even worth to be fixed, I would totally understand that it's not but the error message asked for me to report the bug so I'm here :) )

Thanks in advance

**Comment by nijel** [comment] 2016-07-13 05:59
Duplicate of #222

**Closed by nijel** 2016-07-13 05:59 UTC
